# Generated by Django 3.0.7 on 2020-06-24 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0002_auto_20200623_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
